FEATURE_LABELS = {
    "age_yrs": "Age",
    "weight_kg": "Weight",
    "height_cm": "Height",
    "bmi": "BMI",
    "pulse_rate_bpm": "Pulse Rate",
    "rr_breathsmin": "Respiratory Rate",
    "hb_gdl": "Hemoglobin",
    "cycle_ri": "Cycle Regularity Index",
    "cycle_length_days": "Cycle Length",
    "pregnant_yn": "Pregnancy Status",
    "i_betahcg_miuml": "I Beta-HCG",
    "ii_betahcg_miuml": "II Beta-HCG",
    "fsh_miuml": "FSH",
    "lh_miuml": "LH",
    "lhfsh_ratio": "LH / FSH Ratio",
    "hip_inch": "Hip Circumference",
    "waist_inch": "Waist Circumference",
    "waisthip_ratio": "Waist-to-hip Ratio",
    "tsh_miul": "TSH",
    "amh_ngml": "AMH",
    "prl_ngml": "Prolactin",
    "vit_d3_ngml": "Vitamin D3",
    "prg_ngml": "Progesterone",
    "rbs_mgdl": "Random Blood Sugar",
    "weight_gain_yn": "Recent Weight Gain",
    "hair_growth_yn": "Excess Hair Growth",
    "skin_darkening_yn": "Skin Darkening",
    "hair_loss_yn": "Hair Loss",
    "pimples_yn": "Acne / Pimples",
    "fast_food_yn": "Fast Food Consumption",
    "regexercise_yn": "Regular Exercise",
    "bp_systolic_mmhg": "BP Systolic",
    "bp_diastolic_mmhg": "BP Diastolic",
    "follicle_no_l": "Follicles (left)",
    "follicle_no_r": "Follicles (right)",
    "total_follicles": "Total Antral Follicles",
    "follicles_difference": "Follicle Asymmetry",
    "avg_f_size_l_mm": "Avg Follicle Size (left)",
    "avg_f_size_r_mm": "Avg Follicle Size (right)",
    "endometrium_mm": "Endometrium Thickness",
}
